import "@/app/globals.css";
import Nav from "@/components/nav/Nav";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import NavContextProvider from "@/context/nav-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavContextProvider>
          <Nav />
          <main>{children}</main>
        </NavContextProvider>
        {/* footer */}
      </body>
    </html>
  );
}
