import "@/app/globals.css";
import Nav from "@/components/nav/Nav";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavContextProvider from "@/context/nav-context";
import Footer from "@/components/footer/Footer";
import NextTopLoader from "nextjs-toploader";
import CartProvider from "@/store/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="app" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* top loader */}

        <CartProvider>
          <NextTopLoader
            color="#2299DD"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #2299DD,0 0 5px #2299DD"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />

          <NavContextProvider>
            <Nav />
            {/* button */}

            <main>{children}</main>
            <Footer />
          </NavContextProvider>
        </CartProvider>
      </body>
    </html>
  );
}
